// ================================================================
//  FAITH  -  reference text carried in the firmware itself
// ================================================================
//  Everything here lives in flash (.rodata on the ESP32, which is
//  memory mapped), so it costs no RAM and works with no network.
//
//  Chapter names, meanings, verse counts and revelation place follow
//  the standard Kufan numbering. The themes are short descriptive
//  notes, not tafsir.
// ================================================================
#pragma once

struct Surah { const char* name; const char* meaning; uint16_t ayat; bool makki; const char* theme; };
static const Surah SURAH[114] = {
  { "Al-Fatihah", "The Opening", 7, true,
    "The opening of the Quran and the chapter recited in every unit of prayer. Seven verses that praise Allah as Lord of all the worlds, the Most Merciful, Master of the Day of Judgement, then turn to asking: we worship You alone, we ask You alone for help, guide us along the straight path." },
  { "Al-Baqarah", "The Cow", 286, false,
    "The longest chapter, revealed over many years in Madinah. It sets out guidance for the new community: belief and hypocrisy, the story of Adam, the history of the Children of Israel and the cow they were told to sacrifice, the change of prayer direction to the Kaaba, and long passages on fasting, pilgrimage, marriage, debt and trade. It holds Ayat al-Kursi and closes with a famous supplication." },
  { "Aal-Imran", "The Family of Imran", 200, false,
    "Named after the family of Maryam. It speaks of the birth of Maryam and Isa, invites the People of the Book to common ground, and reflects at length on the battles of Badr and Uhud, drawing lessons from both victory and setback. It urges patience, holding fast together to the rope of Allah, and remembering Him standing, sitting and lying down." },
  { "An-Nisa", "The Women", 176, false,
    "A chapter of rights and responsibilities. It deals with orphans and their property, inheritance shares, marriage, the treatment of women, and justice in the household. It also covers prayer while travelling or in danger, warns against hypocrisy, and calls for standing firmly for justice even against oneself or one's own family." },
  { "Al-Maidah", "The Table Spread", 120, false,
    "Named after the table of food the disciples asked Isa to request from heaven. It opens with fulfilling covenants, covers lawful and unlawful food, ablution, and justice in judgement. It reminds the People of the Book of their covenants, tells the story of the two sons of Adam, and declares that saving one life is like saving all of humanity." },
  { "Al-Anam", "The Cattle", 165, true,
    "A Makkan chapter arguing for the oneness of Allah. It follows Ibrahim as he looks at the star, the moon and the sun and turns away from each towards the One who created them. It answers the objections of the idolaters, criticises their superstitions about cattle, and lists commandments that echo the earlier scriptures." },
  { "Al-Araf", "The Heights", 206, true,
    "Named after the elevated place between Paradise and the Fire. It tells the story of Adam and Iblis in detail, then moves through the messengers: Nuh, Hud, Salih, Lut, Shuayb and Musa. The confrontation with Pharaoh and the magicians is given at length, along with the covenant taken from the children of Adam." },
  { "Al-Anfal", "The Spoils of War", 75, false,
    "Revealed after the battle of Badr. It settles the question of the spoils, describes how a small and poorly equipped group was helped, and sets out the conduct expected in conflict: steadfastness, obedience, unity and inclining to peace when the other side inclines to it." },
  { "At-Tawbah", "The Repentance", 129, false,
    "The only chapter that does not open with the basmalah. It announces the end of treaties with those who broke them, deals with the expedition to Tabuk, exposes the excuses of the hypocrites, and mentions the three who stayed behind and were later forgiven. It closes with warm verses about the Messenger's care for his people." },
  { "Yunus", "Jonah", 109, true,
    "A Makkan chapter on the certainty of the message and the Hereafter. It points to the ordered creation as a sign, recounts Nuh and Musa, and mentions the people of Yunus, the one community that believed in time and was spared. It repeats that guidance cannot be forced on anyone." },
  { "Hud", "Hud", 123, true,
    "A chapter of warnings drawn from history. It gives the fullest account of Nuh and the ark, then Hud with the people of Ad, Salih with Thamud, Ibrahim's guests, Lut, Shuayb and Musa. The Prophet was told this chapter and its sisters had turned his hair grey. It ends with the command to stand firm and be patient." },
  { "Yusuf", "Joseph", 111, true,
    "Called the most beautiful of stories, told from beginning to end in one chapter. The dream of a boy, the jealousy of brothers, the well, the house of the Egyptian minister, prison, the interpretation of the king's dream, and finally the reunion and forgiveness. A study of patience, chastity and how hardship turns." },
  { "Ar-Rad", "The Thunder", 43, false,
    "Named after the thunder that glorifies Allah with praise. It contrasts truth with falsehood using the image of foam carried away by a river while what benefits people remains. It speaks of the angels who guard each person and states that Allah does not change the condition of a people until they change what is in themselves." },
  { "Ibrahim", "Abraham", 52, true,
    "Centred on the prayer of Ibrahim for Makkah and his descendants. It uses the parable of the good word as a firm tree with roots deep and branches in the sky, against the bad word as an uprooted tree. It warns that gratitude brings increase, and describes Shaytan disowning his followers on the Day of Judgement." },
  { "Al-Hijr", "The Rocky Tract", 99, true,
    "Named after the valley home of Thamud. It reassures the Prophet at a difficult time, promising that Allah Himself will preserve this reminder. It retells the creation of Adam, the refusal of Iblis, the guests of Ibrahim, and the fate of Lut's people, then tells the Prophet to proclaim what he is commanded." },
  { "An-Nahl", "The Bee", 128, true,
    "Called the chapter of blessings. It lists gift after gift: cattle, rain, the sun and moon, the sea, and the bee that takes from every fruit and produces a drink of varied colours with healing in it. It commands justice, kindness and giving to relatives, and forbids indecency and oppression." },
  { "Al-Isra", "The Night Journey", 111, true,
    "Opens with the night journey from the Sacred Mosque to the Farthest Mosque. It sets out a list of moral commands: worship none but Allah, be good to parents, do not kill your children out of fear of poverty, do not come near unlawful intimacy, give full measure, and do not walk the earth in arrogance." },
  { "Al-Kahf", "The Cave", 110, true,
    "Four stories that test faith. The young men who slept in the cave for centuries, the owner of two gardens who forgot who gave them, Musa learning patience from a servant of Allah, and Dhul-Qarnayn and the barrier. Widely recited on Fridays. It warns against the trial of wealth, knowledge and power." },
  { "Maryam", "Mary", 98, true,
    "Opens with Zakariyya praying quietly for a child in old age, then the birth of Yahya, then the story of Maryam and the birth of Isa under the palm tree. It also mentions Ibrahim's gentle argument with his father, and closes by rejecting the claim that the Most Merciful has taken a son." },
  { "Ta-Ha", "Ta-Ha", 135, true,
    "A comforting chapter revealed early. It tells Musa's story from the burning bush to the confrontation with Pharaoh, the magicians who believed and would not turn back, the crossing of the sea, and the calf. It also returns to Adam and the whisper of Shaytan, and teaches the prayer: my Lord, increase me in knowledge." },
  { "Al-Anbiya", "The Prophets", 112, true,
    "A gallery of messengers: Ibrahim breaking the idols, Nuh, Dawud and Sulayman judging a case, Ayyub in his illness, Yunus in the belly of the fish, Zakariyya and Maryam. It states that every messenger was sent with the same message, and that the Prophet was sent as a mercy to all the worlds." },
  { "Al-Hajj", "The Pilgrimage", 78, false,
    "Named after the pilgrimage and the call of Ibrahim that still brings people from every distant path. It opens with the shaking of the Hour, uses the stages of human creation and the reviving of dead earth as proof of resurrection, and gives the first permission to defend against persecution." },
  { "Al-Muminun", "The Believers", 118, true,
    "Opens by listing what makes the believers successful: humility in prayer, turning from idle talk, giving zakah, guarding chastity, keeping trusts and promises, and guarding their prayers. It then describes the stages of human creation, recounts Nuh and Musa, and pictures the regret of those who wasted their lives." },
  { "An-Nur", "The Light", 64, false,
    "Contains the verse of light, comparing Allah's light to a lamp in a niche. It sets rules for modesty, lowering the gaze and dress, and deals with the false accusation made against Aisha, warning severely against spreading rumours. It also teaches manners for entering homes and the etiquette of privacy." },
  { "Al-Furqan", "The Criterion", 77, true,
    "Answers the objections raised against the Prophet: why is he an ordinary man, why no treasure, why no angel. It contrasts these with the qualities of the servants of the Most Merciful, who walk humbly, spend without waste, speak peace to the ignorant, and spend part of the night in prayer." },
  { "Ash-Shuara", "The Poets", 227, true,
    "A long sequence of messengers, each with the same refrain of denial and consequence: Musa, Ibrahim, Nuh, Hud, Salih, Lut and Shuayb. It closes by distinguishing revelation from poetry, describing poets who wander in every valley and say what they do not do." },
  { "An-Naml", "The Ants", 93, true,
    "Named after the ant that warned its colony as Sulayman's army approached. It tells of Sulayman, the hoopoe, and the Queen of Sheba who came to believe. It also covers Musa, Salih and Lut, and asks a series of questions about who created the heavens and earth and answers the one in distress." },
  { "Al-Qasas", "The Stories", 88, true,
    "The life of Musa told fully: the baby in the river, growing up in Pharaoh's house, the flight to Madyan, the years with Shuayb, and the return. It also tells of Qarun, whose treasure and arrogance were swallowed by the earth, and reminds that the home of the Hereafter is for those who seek no arrogance." },
  { "Al-Ankabut", "The Spider", 69, true,
    "Opens by stating that people will be tested rather than left to say they believe. The house of the spider is used as the image of relying on anything besides Allah, the frailest of houses. It recounts Nuh, Ibrahim, Lut and Shuayb, and promises guidance to those who strive in His cause." },
  { "Ar-Rum", "The Romans", 60, true,
    "Opens with a prophecy that the defeated Romans would win within a few years, which came true. It then turns to signs in creation: the making of pairs, sleep, lightning, and the diversity of languages and colours. It notes that corruption has appeared on land and sea through what people's hands have earned." },
  { "Luqman", "Luqman", 34, true,
    "Built around the advice a wise father gave his son: do not associate partners with Allah, be grateful to your parents, establish prayer, enjoin good and forbid wrong, be patient, do not turn your cheek away from people in scorn, be modest in your walk and lower your voice." },
  { "As-Sajdah", "The Prostration", 30, true,
    "A short chapter on creation, resurrection and revelation. It describes those whose sides leave their beds to call on their Lord in hope and fear, and says no soul knows what comfort has been kept hidden for them. It is one of the chapters containing a verse of prostration." },
  { "Al-Ahzab", "The Combined Forces", 73, false,
    "Named after the allied armies that besieged Madinah in the battle of the Trench. It records the fear and the steadfastness of that moment, settles questions about adoption and household conduct, describes the Prophet as the seal of the prophets, and lists the qualities of believing men and women side by side." },
  { "Saba", "Sheba", 54, true,
    "Named after the kingdom given gardens on both sides and a warning it ignored, until the dam broke. It mentions the favours given to Dawud and Sulayman, and rejects the excuse of the weak who blamed the arrogant, showing that each will answer for their own choices." },
  { "Fatir", "The Originator", 45, true,
    "Opens with praise for the Originator of the heavens and earth who made the angels messengers with wings. It uses the two seas, one sweet and one salt, and the variety of colours in mountains, people and animals as signs. It reminds that no bearer of burdens carries the burden of another." },
  { "Ya-Sin", "Ya-Sin", 83, true,
    "Often called the heart of the Quran. It tells of a town that rejected its messengers and the one man who came running from the far side of the city to support them. It then gathers signs: dead earth revived, the night stripped of day, the sun running its course, and the ships that sail." },
  { "As-Saffat", "Those Who Set the Ranks", 182, true,
    "Opens with the ranks of angels. It describes the scoffers in the next life, the delights of the sincere, and then a series of prophets. Its centre is Ibrahim's dream of sacrificing his son, the calm reply of the son, and the great ransom that followed. It also mentions Yunus and the fish." },
  { "Sad", "Sad", 88, true,
    "Opens with the objections of the Makkan leaders, then turns to Dawud and the two who came over the wall with a dispute, Sulayman and his horses, and Ayyub and his patience. It ends with the creation of Adam, the refusal of Iblis out of pride, and his request for respite." },
  { "Az-Zumar", "The Troops", 75, true,
    "A chapter on sincerity in worship. It notes how people call on Allah sincerely in distress and forget when relief comes. It contains the verse telling those who have wronged themselves not to despair of the mercy of Allah, and closes with both groups being driven in crowds to their destinations." },
  { "Ghafir", "The Forgiver", 85, true,
    "Opens with the names of Allah as Forgiver of sin and Accepter of repentance. Its heart is the believing man from Pharaoh's own family who hid his faith and spoke up for Musa, arguing carefully and warning his people. It states that Allah answers those who call on Him." },
  { "Fussilat", "Explained in Detail", 54, true,
    "Describes a Quran whose verses are set out clearly. It recounts Ad and Thamud, and pictures the limbs of a person testifying against them. It advises repelling evil with what is better, so that an enemy becomes a close friend, and promises that signs will be shown on the horizons and within themselves." },
  { "Ash-Shura", "The Consultation", 53, true,
    "Named after the practice of deciding matters by mutual consultation, listed among the qualities of the believers. It affirms that the same religion was enjoined on Nuh, Ibrahim, Musa and Isa. It teaches that a wrong may be answered with its like, but forgiving and reconciling carries the greater reward." },
  { "Az-Zukhruf", "The Gold Adornments", 89, true,
    "Answers those who measured prophethood by wealth, pointing out that worldly gold is of so little weight that Allah could have given roofs of silver to the disbelievers. It mentions Ibrahim's word kept among his descendants, Musa before Pharaoh, and Isa as an example, not a deity." },
  { "Ad-Dukhan", "The Smoke", 59, true,
    "A short warning chapter naming a clear smoke as a sign. It mentions the blessed night in which the Quran was sent down, recounts Pharaoh's end, and contrasts the ease of the righteous with the state of those who denied. It ends noting the Quran was made easy in the Prophet's tongue." },
  { "Al-Jathiyah", "The Kneeling", 37, true,
    "Named after the scene of every community kneeling, called to its record. It gathers signs in the heavens, the earth, the rain and the winds, and criticises the one who takes his own desire as his god. It warns against assuming that life is only this world with nothing beyond it." },
  { "Al-Ahqaf", "The Sand Dunes", 35, true,
    "Named after the dunes where the people of Ad lived. It includes a strong instruction to be good to parents, describing the difficulty of pregnancy and nursing and teaching a prayer of gratitude at the age of forty. It also records a group of jinn who listened to the Quran and believed." },
  { "Muhammad", "Muhammad", 38, false,
    "Also called the chapter of fighting. Revealed as the community in Madinah faced open conflict, it contrasts those who believe and do good with those who obstruct the path. It describes the gardens promised, exposes the hesitation of the hypocrites, and warns against turning away and being replaced by another people." },
  { "Al-Fath", "The Victory", 29, false,
    "Revealed after the treaty of Hudaybiyyah, which looked like a setback and is called a clear victory. It records the pledge given under the tree, the tranquillity sent down into the hearts of the believers, and the true dream of entering the Sacred Mosque in safety. It ends describing the Prophet and his companions." },
  { "Al-Hujurat", "The Private Rooms", 18, false,
    "A short chapter of manners that shaped a community. Do not raise your voices above the Prophet's, verify news before acting on it, make peace between quarrelling groups, do not mock, do not use offensive nicknames, avoid suspicion, do not spy, do not backbite. It states that people were made into nations to know one another, and the most honoured is the most mindful of Allah." },
  { "Qaf", "Qaf", 45, true,
    "A powerful chapter on resurrection, often recited at Friday and Eid prayers. It describes Allah as nearer to a person than their jugular vein, with two recording angels seated on either side. It pictures the day the earth splits and everyone comes forth, and asks whether the earlier peoples were stronger." },
  { "Adh-Dhariyat", "The Winnowing Winds", 60, true,
    "Opens with oaths by the scattering winds. It describes the guests of Ibrahim and the good news of a son, the end of Lut's people, Pharaoh, Ad and Thamud. It states plainly that jinn and mankind were created only to worship Him, and that provision is with Allah in the heaven." },
  { "At-Tur", "The Mount", 49, true,
    "Opens with oaths by the mountain and by a book inscribed. It describes the ease of those admitted to the gardens, joined by their offspring, and then puts a series of questions to the deniers: were they created from nothing, did they create the heavens, do they own the treasures of their Lord." },
  { "An-Najm", "The Star", 62, true,
    "Opens by swearing by the star as it sets, affirming that the Prophet does not speak from desire. It describes the vision at the lote tree of the farthest boundary. It rejects the idols named by the Makkans, and states that a person will have nothing except what they strive for." },
  { "Al-Qamar", "The Moon", 55, true,
    "Opens with the splitting of the moon. It moves through Nuh, Ad, Thamud, the people of Lut and Pharaoh, each with the same refrain: We have made the Quran easy to remember, so is there anyone who will take heed. It closes promising the mindful gardens and rivers in a seat of truth." },
  { "Ar-Rahman", "The Most Merciful", 78, false,
    "Known for its refrain, so which of the favours of your Lord will you deny, repeated thirty one times. It begins with the teaching of the Quran and the creation of man, then lists favour after favour in the sky, the sea and the earth, before describing the gardens in detail." },
  { "Al-Waqiah", "The Inevitable", 96, true,
    "Divides people into three groups on the Day of Judgement: the foremost, the companions of the right and the companions of the left. It describes the state of each, then points to the seed that is planted, the water that is drunk and the fire that is kindled, asking who is truly responsible." },
  { "Al-Hadid", "The Iron", 29, false,
    "Named after iron, sent down with strength and benefits for people. It urges spending in the cause of Allah before hardship, asks whether the time has not come for hearts to become humble, and pictures the believers with their light running before them while the hypocrites are left behind." },
  { "Al-Mujadila", "The Pleading Woman", 22, false,
    "Opens with a woman who argued her case about her marriage and was answered from above the seven heavens. It corrects an old custom of divorce, teaches manners for private conversation and for making room in gatherings, and states that Allah raises in rank those given knowledge." },
  { "Al-Hashr", "The Exile", 24, false,
    "Records the removal of a treacherous tribe from Madinah without fighting. It praises the Ansar who preferred others over themselves even while in need, and closes with a passage of the names of Allah: the Sovereign, the Holy, the Source of Peace, the Creator, the Fashioner." },
  { "Al-Mumtahanah", "She Who Is Tested", 13, false,
    "Deals with loyalty and its limits. It forbids taking as allies those who fought against the believers and drove them out, while permitting kindness and justice to those who did not. It holds up Ibrahim as an example, and sets out the pledge taken from believing women." },
  { "As-Saff", "The Ranks", 14, false,
    "Opens with everything in the heavens and earth glorifying Allah, then asks why people say what they do not do. It records Musa's words to his people and the good news Isa gave of a messenger to come after him. It calls the believers to a trade that saves them from a painful punishment, and to be helpers of Allah." },
  { "Al-Jumuah", "The Friday", 11, false,
    "A short chapter on the Friday gathering. It criticises those given a scripture who did not carry it, using the image of a donkey carrying books. It instructs believers to hurry to the remembrance of Allah when the call is made and leave off trade, then to spread out and seek His bounty afterwards." },
  { "Al-Munafiqun", "The Hypocrites", 11, false,
    "Describes the hypocrites of Madinah: their fine appearance, their persuasive speech, their oaths used as a shield, and their refusal to be prayed for. It ends warning the believers not to let wealth or children distract them from the remembrance of Allah, and to spend before death comes and the excuse is too late." },
  { "At-Taghabun", "The Mutual Loss and Gain", 18, false,
    "Named after the day when the true gains and losses become clear. It affirms that no misfortune occurs except by permission, and that the heart guided through it is the one that believed. It warns that wealth and children are a trial, and urges being mindful as much as one is able." },
  { "At-Talaq", "The Divorce", 12, false,
    "Sets out the procedure for divorce with care: the waiting period, the housing and maintenance during it, and the treatment of a pregnant or nursing wife. Its refrain is that whoever is mindful of Allah is given a way out and provided from where they did not expect." },
  { "At-Tahrim", "The Prohibition", 12, false,
    "Opens with an incident in the Prophet's household and turns it into general guidance. It calls believers to protect themselves and their families from the Fire, teaches a prayer of sincere repentance, and gives four examples: the wives of Nuh and Lut, the wife of Pharaoh, and Maryam." },
  { "Al-Mulk", "The Sovereignty", 30, true,
    "Often recited before sleep. It opens with the One in whose hand is all dominion, who created death and life to test who is best in deed. It invites the reader to look again and again at the sky and find no flaw, and asks who would provide if the provision were withheld." },
  { "Al-Qalam", "The Pen", 52, true,
    "Opens with an oath by the pen and what is written, defending the Prophet's character. It lists the traits of the one not to be obeyed: the habitual swearer, the backbiter, the one who withholds good. It tells of the garden owners who planned to harvest at dawn and keep the poor away, and found it stripped bare." },
  { "Al-Haqqah", "The Reality", 52, true,
    "Names the Day of Judgement as the inevitable reality. It recalls Thamud, Ad, Pharaoh and the overturned cities, then describes the blast of the trumpet, the sky splitting and the records given in the right hand or behind the back, with the words spoken in each case." },
  { "Al-Maarij", "The Ascending Stairways", 44, true,
    "Describes a day whose length is beyond ordinary measure, when a guilty person would ransom himself with everyone he knows. It notes that man was created anxious, panicking in hardship and withholding in ease, except those constant in prayer who set aside a known right for the one who asks and the one deprived." },
  { "Nuh", "Noah", 28, true,
    "Devoted entirely to Nuh and his long call. He describes calling his people by night and by day, openly and in private, urging them to seek forgiveness so that rain, wealth and children would follow. He points to the seven heavens, the moon as a light and the sun as a lamp, and finally makes his supplication." },
  { "Al-Jinn", "The Jinn", 28, true,
    "Records a group of jinn who listened to the Quran and told their people they had heard something wonderful. It corrects their old beliefs, states that the places of worship belong to Allah alone, and describes the Prophet as one who calls upon his Lord and owns no harm or benefit for anyone." },
  { "Al-Muzzammil", "The Enwrapped One", 20, true,
    "Addressed to the Prophet wrapped in his cloak, calling him to stand in prayer at night, for a weighty word was about to be placed on him. The early command to pray much of the night was later eased in the closing verse, which acknowledges illness, travel and work." },
  { "Al-Muddaththir", "The Cloaked One", 56, true,
    "One of the earliest revelations, telling the Prophet to arise and warn, to magnify his Lord and to keep his garments pure. It describes a man who thought and calculated before dismissing the Quran as mere magic, and asks the people of the Fire what brought them there, receiving a plain answer." },
  { "Al-Qiyamah", "The Resurrection", 40, true,
    "Opens by swearing by the Day of Resurrection and by the self-reproaching soul. It asks whether man thinks his bones will never be gathered, and answers that Allah is able to shape even his fingertips. It describes the moment the eyes are dazzled and the soul reaches the collarbone." },
  { "Al-Insan", "Man", 31, false,
    "Also called Al-Dahr. It opens by asking whether there was a time when man was not a thing worth mentioning. It praises those who give food, despite loving it, to the needy, the orphan and the captive, seeking only the face of Allah, and describes the gardens, silk and springs prepared for them." },
  { "Al-Mursalat", "Those Sent Forth", 50, true,
    "Opens with oaths by the winds sent forth. Its refrain, woe that day to the deniers, is repeated ten times. It recalls the origin of man from a humble fluid, the earth made to hold the living and the dead, and the mountains set firm, asking whether the One who made all this cannot restore it." },
  { "An-Naba", "The Great News", 40, true,
    "Opens by asking what people are questioning one another about, and answers with the great news they dispute. It then lists the settled order of the world: the earth as a resting place, mountains as pegs, sleep for rest, night as covering, day for livelihood, and a blazing lamp above." },
  { "An-Naziat", "Those Who Pull Out", 46, true,
    "Opens with oaths by the angels. It recounts Musa's mission to Pharaoh, who claimed to be the highest lord and was seized. It then turns to creation, the sky raised and the earth spread with its water and pasture, and ends with the question of when the Hour will come, which only Allah knows." },
  { "Abasa", "He Frowned", 42, true,
    "Opens with a gentle correction after a blind man seeking knowledge was passed over for a group of Makkan leaders. It reminds that the one who comes striving and in awe deserves attention. It then describes the food that grows from split earth, and the day a person flees from his own family." },
  { "At-Takwir", "The Folding Up", 29, true,
    "Describes the unmaking of the world: the sun folded up, the stars falling, the mountains moved, the seas set on fire and the scrolls laid open. It then affirms the truthfulness of the revelation and the one who brought it, and asks where the reader is going, for this is a reminder to all." },
  { "Al-Infitar", "The Cleaving", 19, true,
    "A short chapter on the splitting of the sky and the scattering of the stars. It asks what deceived man about his generous Lord, who created him, proportioned him and balanced him. It mentions the honourable scribes who record, and states that on that day no soul will have power over another." },
  { "Al-Mutaffifin", "Those Who Deal in Fraud", 36, true,
    "Opens with a warning to those who take full measure from others but give less when they measure out. It describes the records of the wicked and the righteous, and pictures those who used to laugh at the believers finding the situation reversed, with the believers on couches looking on." },
  { "Al-Inshiqaq", "The Splitting Open", 25, true,
    "Describes the sky splitting and the earth flattening, throwing out what is within it. It states that man is labouring towards his Lord and will meet Him, and gives the record in the right hand or behind the back. It swears by the twilight, the night and the moon that people move from stage to stage." },
  { "Al-Buruj", "The Great Constellations", 22, true,
    "Recalls the people of the ditch who burned believers alive for nothing but their faith. It reassures those persecuted in Makkah that the same pattern has happened before and that the Lord's grip is severe. It closes affirming a glorious Quran preserved in a guarded tablet." },
  { "At-Tariq", "The Night Comer", 17, true,
    "Opens by swearing by the sky and the night visitor, the piercing star, stating that every soul has a keeper over it. It asks man to look at what he was created from, and affirms that the One who began him can return him on the day secrets are tested." },
  { "Al-Ala", "The Most High", 19, true,
    "Opens with the command to glorify the name of your Lord, the Most High, who created and proportioned, measured and guided. It promises the Prophet he will be made to recite and not forget, notes that the reminder benefits whoever is mindful, and says the same was in the scrolls of Ibrahim and Musa." },
  { "Al-Ghashiyah", "The Overwhelming", 26, true,
    "Contrasts two faces on that day, one weary and one pleased. It then turns outwards with a famous invitation: do they not look at the camels, how they were created, at the sky how it was raised, the mountains how they were fixed, the earth how it was spread. The Prophet is a reminder, not a controller." },
  { "Al-Fajr", "The Dawn", 30, true,
    "Swears by the dawn and ten nights. It recalls Ad of the lofty pillars, Thamud who carved the rocks, and Pharaoh of the stakes. It corrects the assumption that wealth means honour and poverty means disgrace, criticises neglect of the orphan and the poor, and calls the contented soul home in peace." },
  { "Al-Balad", "The City", 20, true,
    "Swears by Makkah, the Prophet's own city. It says man was created in struggle, and asks whether he thinks no one sees him. It then describes the steep path he has not attempted: freeing a slave, feeding on a day of hunger an orphan relative or a poor person in the dust." },
  { "Ash-Shams", "The Sun", 15, true,
    "A series of oaths by the sun, the moon, the day, the night, the sky, the earth and the soul, leading to a single point: successful is the one who purifies it, and failed is the one who buries it. It then recalls Thamud and the she-camel they hamstrung in their arrogance." },
  { "Al-Layl", "The Night", 21, true,
    "Swears by the night, the day and the creation of male and female, then divides people by two paths. The one who gives, is mindful and believes in the best is eased towards ease. The one who withholds and thinks himself self-sufficient is eased towards hardship. Wealth will not help him when he falls." },
  { "Ad-Duha", "The Morning Brightness", 11, true,
    "Revealed after a pause in revelation, reassuring the Prophet that his Lord had not abandoned him nor was displeased. It reminds him of being an orphan and given shelter, lost and guided, in need and enriched. It then instructs him not to oppress the orphan, not to repel the beggar, and to speak of his Lord's favour." },
  { "Ash-Sharh", "The Relief", 8, true,
    "A short continuation of the same comfort. It asks whether the Prophet's chest was not expanded and his burden removed. Its heart is the repeated promise that with hardship comes ease, stated twice. It ends telling him that when he is free he should devote himself to his Lord." },
  { "At-Tin", "The Fig", 8, true,
    "Swears by the fig and the olive, by Mount Sinai and by this secure city. It states that man was created in the best of forms, then reduced to the lowest of the low, except those who believe and do righteous deeds. It closes by asking whether Allah is not the most just of judges." },
  { "Al-Alaq", "The Clot", 19, true,
    "Contains the very first revelation: read in the name of your Lord who created, created man from a clinging clot, read and your Lord is the most generous, who taught by the pen. The rest, revealed later, describes the man who transgresses when he considers himself self-sufficient and forbids another from praying." },
  { "Al-Qadr", "The Night of Decree", 5, true,
    "Five short verses about the night in which the Quran was sent down, a night better than a thousand months. The angels and the Spirit descend in it by permission of their Lord with every decree, and it is peace until the break of dawn." },
  { "Al-Bayyinah", "The Clear Evidence", 8, false,
    "States that the People of the Book and the idolaters were not to be left until clear evidence came to them, a messenger reciting purified scriptures. It notes that they only divided after knowledge reached them, and sums up the command: worship Allah sincerely, establish prayer and give zakah." },
  { "Az-Zalzalah", "The Earthquake", 8, false,
    "Describes the earth shaking with its final quake, throwing out its burdens, and reporting its news because its Lord inspired it. It ends with two of the most quoted verses: whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it." },
  { "Al-Adiyat", "The Chargers", 11, true,
    "Opens with oaths by charging horses that strike sparks and raise dust at dawn. It then states that man is ungrateful to his Lord and a witness to that himself, and intense in his love of wealth. It closes by asking whether he does not know that what is in the graves will be scattered and what is in the breasts made known." },
  { "Al-Qariah", "The Striking Calamity", 11, true,
    "Names the Day of Judgement as the striking calamity. It pictures people like scattered moths and mountains like carded wool, then describes the scales: the one whose scales are heavy will be in a pleasant life, and the one whose scales are light will have the Pit as his home." },
  { "At-Takathur", "The Rivalry", 8, true,
    "A short and sharp chapter on competing for more and more, which distracts people until they visit the graves. It repeats the warning that they will come to know, and states that if they knew with certainty they would see the Fire. It ends saying they will be questioned that day about the pleasures they enjoyed." },
  { "Al-Asr", "The Time", 3, true,
    "Three verses that summarise the whole message. By time, man is in loss, except those who believe, do righteous deeds, and advise one another to truth and advise one another to patience. Companions of the Prophet would recite it to one another before parting." },
  { "Al-Humazah", "The Slanderer", 9, true,
    "A warning to every backbiter and slanderer who gathers wealth and counts it, thinking it will make him last forever. It describes the crushing Fire kindled by Allah which rises over the hearts, and pictures it closing in upon them in extended columns." },
  { "Al-Fil", "The Elephant", 5, true,
    "Recalls the army that came with an elephant to destroy the Kaaba in the year of the Prophet's birth. It asks whether the reader has not considered how their plan was made to fail, with flocks of birds sent against them, leaving them like chewed straw." },
  { "Quraysh", "Quraysh", 4, true,
    "Follows directly from the previous chapter. Because of the security granted to Quraysh and their trading caravans in winter and summer, they are told to worship the Lord of this House, who fed them against hunger and gave them safety against fear." },
  { "Al-Maun", "The Small Kindnesses", 7, true,
    "Asks who it is that denies the religion, and answers: the one who pushes away the orphan and does not encourage feeding the poor. It then warns those who pray while heedless of their prayer, who do it to be seen, and who withhold even small acts of kindness and simple assistance." },
  { "Al-Kawthar", "The Abundance", 3, true,
    "The shortest chapter in the Quran. It tells the Prophet that he has been granted abundance, instructs him to pray to his Lord and sacrifice, and states that the one who hates him is the one cut off. Revealed as comfort when he was mocked for having no surviving son." },
  { "Al-Kafirun", "The Disbelievers", 6, true,
    "A clear statement of separation in belief, given when the Makkans proposed taking turns in worship. Say: I do not worship what you worship, and you do not worship what I worship. It ends with a line often quoted for coexistence without compromise: for you your religion, and for me mine." },
  { "An-Nasr", "The Divine Support", 3, false,
    "One of the last chapters revealed. When the help of Allah and the victory come, and you see people entering the religion in crowds, then glorify the praise of your Lord and seek His forgiveness, for He is ever accepting of repentance. Understood as a sign the Prophet's work was nearing its end." },
  { "Al-Masad", "The Palm Fibre", 5, true,
    "Names Abu Lahab, an uncle who was among the fiercest opponents of the message, and states that neither his wealth nor his gains will help him. It mentions his wife, the carrier of firewood, with a rope of twisted palm fibre around her neck." },
  { "Al-Ikhlas", "The Sincerity", 4, true,
    "Four verses said to equal a third of the Quran in meaning. Say: He is Allah, One, the Eternal Refuge. He neither begets nor is born, and there is nothing comparable to Him. Revealed when the Makkans asked the Prophet to describe his Lord's lineage." },
  { "Al-Falaq", "The Daybreak", 5, true,
    "The first of the two chapters of refuge. Seeking protection with the Lord of the daybreak from the evil of what He created, from the darkness when it settles, from those who blow on knots, and from an envier when he envies. Recited morning and evening and before sleep." },
  { "An-Nas", "Mankind", 6, true,
    "The final chapter of the Quran. Seeking refuge with the Lord of mankind, the King of mankind, the God of mankind, from the evil of the retreating whisperer who whispers in the breasts of people, whether from among the jinn or mankind. Paired with the chapter before it." },
};

struct DivineName { const char* name; const char* meaning; };
static const DivineName NAME99[99] = {
  { "Ar-Rahman", "The Most Compassionate" },
  { "Ar-Rahim", "The Most Merciful" },
  { "Al-Malik", "The King" },
  { "Al-Quddus", "The Most Holy" },
  { "As-Salam", "The Source of Peace" },
  { "Al-Mumin", "The Giver of Faith" },
  { "Al-Muhaymin", "The Guardian" },
  { "Al-Aziz", "The Almighty" },
  { "Al-Jabbar", "The Compeller" },
  { "Al-Mutakabbir", "The Supreme" },
  { "Al-Khaliq", "The Creator" },
  { "Al-Bari", "The Originator" },
  { "Al-Musawwir", "The Fashioner" },
  { "Al-Ghaffar", "The Ever Forgiving" },
  { "Al-Qahhar", "The Subduer" },
  { "Al-Wahhab", "The Bestower" },
  { "Ar-Razzaq", "The Provider" },
  { "Al-Fattah", "The Opener" },
  { "Al-Alim", "The All Knowing" },
  { "Al-Qabid", "The Withholder" },
  { "Al-Basit", "The Extender" },
  { "Al-Khafid", "The Abaser" },
  { "Ar-Rafi", "The Exalter" },
  { "Al-Muizz", "The Giver of Honour" },
  { "Al-Muzill", "The Giver of Dishonour" },
  { "As-Sami", "The All Hearing" },
  { "Al-Basir", "The All Seeing" },
  { "Al-Hakam", "The Judge" },
  { "Al-Adl", "The Utterly Just" },
  { "Al-Latif", "The Subtle and Kind" },
  { "Al-Khabir", "The All Aware" },
  { "Al-Halim", "The Forbearing" },
  { "Al-Azim", "The Magnificent" },
  { "Al-Ghafur", "The Much Forgiving" },
  { "Ash-Shakur", "The Most Appreciative" },
  { "Al-Ali", "The Most High" },
  { "Al-Kabir", "The Most Great" },
  { "Al-Hafiz", "The Preserver" },
  { "Al-Muqit", "The Sustainer" },
  { "Al-Hasib", "The Reckoner" },
  { "Al-Jalil", "The Majestic" },
  { "Al-Karim", "The Most Generous" },
  { "Ar-Raqib", "The Watchful" },
  { "Al-Mujib", "The Responsive" },
  { "Al-Wasi", "The All Encompassing" },
  { "Al-Hakim", "The All Wise" },
  { "Al-Wadud", "The Most Loving" },
  { "Al-Majid", "The Most Glorious" },
  { "Al-Baith", "The Resurrector" },
  { "Ash-Shahid", "The Witness" },
  { "Al-Haqq", "The Absolute Truth" },
  { "Al-Wakil", "The Trustee" },
  { "Al-Qawiyy", "The All Strong" },
  { "Al-Matin", "The Firm" },
  { "Al-Waliyy", "The Protecting Friend" },
  { "Al-Hamid", "The Praiseworthy" },
  { "Al-Muhsi", "The Accounter" },
  { "Al-Mubdi", "The Originator" },
  { "Al-Muid", "The Restorer" },
  { "Al-Muhyi", "The Giver of Life" },
  { "Al-Mumit", "The Bringer of Death" },
  { "Al-Hayy", "The Ever Living" },
  { "Al-Qayyum", "The Sustainer of All" },
  { "Al-Wajid", "The Finder" },
  { "Al-Majid", "The Noble" },
  { "Al-Wahid", "The One" },
  { "Al-Ahad", "The Unique" },
  { "As-Samad", "The Eternal Refuge" },
  { "Al-Qadir", "The Capable" },
  { "Al-Muqtadir", "The Powerful" },
  { "Al-Muqaddim", "The Expediter" },
  { "Al-Muakhkhir", "The Delayer" },
  { "Al-Awwal", "The First" },
  { "Al-Akhir", "The Last" },
  { "Az-Zahir", "The Manifest" },
  { "Al-Batin", "The Hidden" },
  { "Al-Wali", "The Governor" },
  { "Al-Mutaali", "The Most Exalted" },
  { "Al-Barr", "The Source of Goodness" },
  { "At-Tawwab", "The Accepter of Repentance" },
  { "Al-Muntaqim", "The Avenger" },
  { "Al-Afuww", "The Pardoner" },
  { "Ar-Rauf", "The Most Kind" },
  { "Malik-ul-Mulk", "Owner of All Dominion" },
  { "Dhul-Jalali wal-Ikram", "Lord of Majesty and Honour" },
  { "Al-Muqsit", "The Equitable" },
  { "Al-Jami", "The Gatherer" },
  { "Al-Ghaniyy", "The Self Sufficient" },
  { "Al-Mughni", "The Enricher" },
  { "Al-Mani", "The Preventer" },
  { "Ad-Darr", "The Distresser" },
  { "An-Nafi", "The Benefiter" },
  { "An-Nur", "The Light" },
  { "Al-Hadi", "The Guide" },
  { "Al-Badi", "The Incomparable" },
  { "Al-Baqi", "The Everlasting" },
  { "Al-Warith", "The Inheritor" },
  { "Ar-Rashid", "The Guide to the Right Path" },
  { "As-Sabur", "The Most Patient" },
};

struct Dhikr { const char* title; const char* body; };
static const Dhikr MORNING[11] = {
  { "Ayat al-Kursi",
    "Recite Ayat al-Kursi, verse 255 of Al-Baqarah, once. Allah, there is no god but He, the Ever Living, the Sustainer of all. Neither drowsiness nor sleep overtakes Him. Whoever recites it in the morning is under protection until the evening." },
  { "The Three Quls",
    "Recite Al-Ikhlas, Al-Falaq and An-Nas three times each. Say: He is Allah, One. Say: I seek refuge with the Lord of the daybreak. Say: I seek refuge with the Lord of mankind. They suffice against all harm." },
  { "Morning words",
    "Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah. We have entered the morning and the whole kingdom belongs to Allah. Praise is for Allah. There is no god but Allah alone, with no partner." },
  { "Istighfar",
    "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana ala ahdika wa wadika mastatatu. O Allah, You are my Lord. There is no god but You. You created me and I am Your servant. I keep Your covenant as best I can. I seek refuge in You from the evil I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for none forgives sins but You." },
  { "Contentment",
    "Raditu billahi rabban, wa bil islami dinan, wa bi Muhammadin nabiyyan. I am content with Allah as my Lord, with Islam as my religion, and with Muhammad as my Prophet. Say it three times." },
  { "O Ever Living",
    "Ya Hayyu ya Qayyum, bi rahmatika astaghith, aslih li shani kullahu wa la takilni ila nafsi tarfata ayn. O Ever Living, O Sustainer of all, by Your mercy I seek help. Set right all my affairs and do not leave me to myself even for the blink of an eye." },
  { "Against harm",
    "Bismillahil ladhi la yadurru maa ismihi shayun fil ardi wa la fis samai wa huwas Samiul Alim. In the name of Allah, with whose name nothing on earth or in the heaven can cause harm, and He is the All Hearing, the All Knowing. Say it three times." },
  { "Glory to Allah",
    "Subhanallahi wa bihamdih. Glory is to Allah and praise is His. Said one hundred times in a day, it is said that no one will come with better than it, except one who said the same or more." },
  { "Wellbeing",
    "Allahumma inni asalukal afwa wal afiyah fid dunya wal akhirah. O Allah, I ask You for pardon and wellbeing in this world and the next. Ask for it in your religion, your worldly life, your family and your wealth." },
  { "Good of the day",
    "Allahumma inni asaluka khayra hadhal yawm, fathahu wa nasrahu wa nurahu wa barakatahu wa hudah. O Allah, I ask You for the good of this day, its opening, its help, its light, its blessing and its guidance." },
  { "Countless glory",
    "Subhanallahi wa bihamdihi adada khalqih, wa rida nafsih, wa zinata arshih, wa midada kalimatih. Glory and praise be to Allah as many times as the number of His creation, as befits His pleasure, as the weight of His throne and as the ink of His words. Say it three times." },
};
#define MORNING_N 11

static const Dhikr EVENING[11] = {
  { "Ayat al-Kursi",
    "Recite Ayat al-Kursi, verse 255 of Al-Baqarah, once. Allah, there is no god but He, the Ever Living, the Sustainer of all. His throne extends over the heavens and the earth, and guarding them does not tire Him. Whoever recites it in the evening is under protection until the morning." },
  { "The Three Quls",
    "Recite Al-Ikhlas, Al-Falaq and An-Nas three times each. Blow lightly into the palms and wipe over the body, as was the practice before sleep. They suffice against all harm." },
  { "Evening words",
    "Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah. We have entered the evening and the whole kingdom belongs to Allah. Praise is for Allah. There is no god but Allah alone, with no partner." },
  { "Istighfar",
    "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana ala ahdika wa wadika mastatatu. O Allah, You are my Lord. There is no god but You. You created me and I am Your servant. I seek refuge in You from the evil I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for none forgives sins but You." },
  { "Refuge at night",
    "Audhu bi kalimatillahit tammati min sharri ma khalaq. I seek refuge in the perfect words of Allah from the evil of what He has created. Said three times in the evening, it is a shelter for the night." },
  { "Against harm",
    "Bismillahil ladhi la yadurru maa ismihi shayun fil ardi wa la fis samai wa huwas Samiul Alim. In the name of Allah, with whose name nothing on earth or in the heaven can cause harm, and He is the All Hearing, the All Knowing. Say it three times." },
  { "For the night",
    "Allahumma inni asaluka khayra hadhihil laylah, fathaha wa nasraha wa nuraha wa barakataha wa hudaha. O Allah, I ask You for the good of this night, its opening, its help, its light, its blessing and its guidance." },
  { "Before sleep",
    "Allahumma aslamtu nafsi ilayk, wa fawwadtu amri ilayk, wa aljatu zahri ilayk, raghbatan wa rahbatan ilayk. O Allah, I submit myself to You, I entrust my affair to You, and I turn my back to You in hope and in fear of You. There is no refuge from You except with You." },
  { "Contentment",
    "Raditu billahi rabban, wa bil islami dinan, wa bi Muhammadin nabiyyan. I am content with Allah as my Lord, with Islam as my religion, and with Muhammad as my Prophet. Say it three times." },
  { "Istighfar again",
    "Astaghfirullaha wa atubu ilayh. I seek the forgiveness of Allah and I turn to Him in repentance. Said one hundred times in a day, closing the day with it settles the heart." },
  { "On lying down",
    "Bismika Allahumma amutu wa ahya. In Your name, O Allah, I die and I live. Said on lying down. On waking, the words are: praise is for Allah who gave us life after He caused us to die, and to Him is the return." },
};
#define EVENING_N 11

// The tasbih after prayer: three sets of thirty three, then one to
// round it to a hundred. The last is long, so it scrolls.
struct ZikrStep { const char* text; const char* meaning; uint8_t count; };
static const ZikrStep ZIKR[4] = {
  { "SubhanAllah", "Glory be to Allah", 33 },
  { "Alhamdulillah", "All praise is for Allah", 33 },
  { "Allahu Akbar", "Allah is the Greatest", 33 },
  { "La ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa ala kulli shayin qadeer",
    "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is able to do all things.", 1 },
};
#define ZIKR_N 4

